#!/bin/bash

echo "=== Manual Coordinator Deployment Instructions ==="
echo ""
echo "Since SSH requires authentication, follow these steps manually:"
echo ""
echo "1. Copy files to x104m01:"
echo "   scp build/libs/averageSpeedSITM-MIO.jar swarch@x104m01:/home/swarch/sitm-mio/"
echo "   scp -r proyecto-mio/MIO swarch@x104m01:/home/swarch/sitm-mio/"
echo ""
echo "2. SSH to x104m01:"
echo "   ssh swarch@x104m01"
echo ""
echo "3. Start Coordinator:"
echo "   cd /home/swarch/sitm-mio"
echo "   java -Xmx4g -jar averageSpeedSITM-MIO.jar coordinator.CoordinatorNode &"
echo "   echo \$! > coordinator.pid"
echo ""
echo "4. Verify it's running:"
echo "   ps aux | grep CoordinatorNode"
echo "   netstat -tlnp | grep 10000"
echo ""
echo "=== Coordinator should be running on tcp -h x104m01 -p 10000 ==="

